= Introduction
ifndef::book[]
Emeric Martineau
:showtitle:
:page-title: Introduction
:page-description: Introduction du guide
:page-layout: index
endif::[]

Lorsque j'ai voulu me lancer dans le photovoltaïque, je ne trouvais pas par quoi commencer.
J'ai eu la chance de rencontrer des gens qui avaient fait l'installation par eux même, toutefois, il me restait encore de nombreuses questions.

Par ce guide, j'ai voulu essayer de faire le guide que j'aurai aimé avoir à ce moment là. 
Un guide qui explique de façon générale comment fonctionne le photovoltaïque mais aussi de façon beaucoup plus poussée car j'aime comprendre comment fonctionnent les choses.

C'est un guide qui a pour but de donner quelques clefs ou directions pour lancer votre projet.
Il a fallu faire des choix tant pour faciliter les explications que pour amener le lecteur progressivement dans le sujet.

J'ai donc pris le parti d'orienter la présentation dans le cas d'un propriétaire de maison, dans une assez grande ville.
De ce fait, j'ai laissé de côté le système de batteries ainsi que le sujet de l'autonomie totale en électricité.
J'ai aussi fait le choix de présenter la solution la plus simple à mettre en œuvre, celle avec micro-onduleur car pour une première installation, il y a déjà beaucoup à apprendre et comprendre.

Aussi, après lecture de ce guide, il vous faudra certainement creuser le sujet sur des forums comme le https://forum-photovoltaique.fr[Forum photovoltaïque].

== Où trouver la dernière version de ce document

Vous pouvez télécharger la dernière version de ce document à l'adresse suivante https://github.com/emeric-martineau/guide-photovoltaique/releases

== Licence

Ce document est licencié sous Attribution-NonCommercial-ShareAlike 4.0 International © 2024 by Emeric MARTINEAU.

Vous pouvez avoir une copie de cette licence sur http://creativecommons.org/licenses/by-nc-sa/4.0/.

Vous êtes autorisé à :

* Partager — copier, distribuer et communiquer le matériel par tous moyens et sous tous formats
* Adapter — remixer, transformer et créer à partir du matériel
* L'Offrant ne peut retirer les autorisations concédées par la licence tant que vous appliquez les termes de cette licence.

Selon les conditions suivantes :

* Attribution — Vous devez créditer l'œuvre, intégrer un lien vers la licence et indiquer si des modifications ont été effectuées à l'œuvre. Vous devez indiquer ces informations par tous les moyens raisonnables, sans toutefois suggérer que l'Offrant vous soutient ou soutient la façon dont vous avez utilisé son œuvre.
* Pas d'Utilisation Commerciale — Vous n'êtes pas autorisé à faire un usage commercial de cette œuvre, tout ou partie du matériel la composant.
* Partage dans les Mêmes Conditions — Dans le cas où vous effectuez un remix, que vous transformez, ou créez à partir du matériel composant l'œuvre originale, vous devez diffuser l'œuvre modifiée dans les même conditions, c'est à dire avec la même licence avec laquelle l'œuvre originale a été diffusée.
* Pas de restrictions complémentaires — Vous n'êtes pas autorisé à appliquer des conditions légales ou des mesures techniques qui restreindraient légalement autrui à utiliser l'œuvre dans les conditions décrites par la licence.