= Kit photovoltaïque à brancher
ifndef::toc-title[]
:showtitle:
:page-title: Kit photovoltaïque à brancher
:page-description: Que faut-il pour brancher un kit solaire ?
:page-layout: page
endif::[]

Les kits photovoltaïque ont l'avantage d'être simple à installer puisqu'ils sont simplement à brancher sur une prise électrique.

Le but de ces kits prêt à brancher est de permettre aux personnes de s'initier à l'énergie solaire et réduire un peu la facture d'électricité.

Comme vu dans la section file://points-administratif-a-connaitre-dans-tous-les-cas.adoc[Points administratif à connaitre dans tous les cas], si vous posez au sol un kit solaire, la seule démarche à faire, est de créer un compte sur le site d'https://connect-racco.enedis.fr[Enedis Raccordement] et de remplir la demande d'une CACSI.

Il faudra, bien sélectionner le fait que c'est un kit solaire et donc sans création de nouvelle ligne (passage du Consuel inutile, voir *Réaliser soi même une installation*).

== Les inconvénients, faux, qu'on peut nous dire

Sur internet, des articles parlant des inconvénients des kits photovoltaïques peuvent être lus. Il est intéressant de voir que certains articles sont rédigés par des entreprises qui proposent la pose de système solaire. Est-ce dans l'intérêt de ces entreprises de vanter l'achat de ces kits prêt à l'emploi ?

Voici 3 articles que l'on peut lire sur internet :

* https://www.neozone.org/innovation/les-inconvenients-des-panneaux-solaires-plug-play-que-les-vendeurs-oublient-souvent-de-mentionner/[Les inconvénients des panneaux solaires Plug & Play que les vendeurs oublient souvent de mentionner],
* https://o2toit.fr/nos-actualites/solaire/panneaux-solaires-plug-and-play-une-fausse-bonne-idee/[Avantages et inconvénients des panneaux solaires plug and play],
* https://www.solairepro.comparateur-panneau-solaire.fr/pourquoi-les-inconvenients-des-panneaux-photovoltaiques-plug-and-play-doivent-ils-etre-pris-au-serieux/[Pourquoi les inconvénients des panneaux photovoltaïques Plug and Play doivent-ils être pris au sérieux ?].

Basons-nous sur ces articles afin de faire le point et de constater qu'on peut y trouver des idées aussi originales que surprenantes.

=== Production d'électricité limitée

Voilà un inconvénient qui n'a factuellement aucun sens.

Les kits sont des petites installations, leur but n'est pas de couvrir 100% des besoins électrique d'un foyer.

=== Certains facteurs font varier leur efficacité

Exactement comme toutes installations solaires, même réalisées par un professionnel.

=== Impossibilité de revendre le surplus d'électricité

Le but des kits solaires à installer soit même n'est en aucun cas de revendre l'électricité. Alors pourquoi en faire un inconvénient ?

=== Les risques de court-circuit et de surcharge électrique

Voici un nouveau concept :

[quote,Extrait d'un site d'un professionnel du phtovoltaïque]
____
ils vont quand même être branchés sur votre compteur, qui doit respecter certaines normes.
En le branchant vous-même, sauf si vous êtes électricien, vous risquez de provoquer un
court-circuit, ou une surcharge qui ferait disjoncter votre compteur.
____

En France, nous avons la chance d'avoir l'une des meilleurs normes électrique au monde.

Tout appareil électrique doit respecter cette norme pour être vendu en France. Sauf à acheter un produit contrefait ou à un appareil défectueux, il n'y a aucun risque.

Parler de court-circuit est au mieux une ignorance de comment fonctionne les panneaux solaires (et la norme qu'ils doivent respecter en France).

Alors quand on lit cela sur un site d'une entreprise professionnelle dans le photovoltaïque...

Pour ce qui est de la surcharge, c'est en fait un surintensité qu'il peut se produire dans un cas précis.

TODO

=== Augmentation de la dépendance au réseau électrique

On peut lire l'argument suivant :

[quote,Extrait d'un site d'informations générales]
____
Avec une puissance limitée, les utilisateurs des panneaux photovoltaïques
Plug and Play pourraient être davantage dépendants du réseau électrique
traditionnel.
____

Il est impossible qu'en produisant de l'électricité, on augmente sa dépendance au réseau électrique.

C'est suggérer que récupérer l'eau de pluie va faire augmenter sa consommation d'eau sur le réseau d'eau potable.