title: Guide sans prétention du photovoltaïque
description: Un guide permettant de comprendre comment fonctionne le photovoltaïque, les démarches, les devis ou même poser soi-même
subtitle: 'To update'
show_downloads: true
exclude:
- LICENSE
- README.md
- Gemfile
- Gemfile.lock
- Rakefile
- Dockerfile
- '*.sh'
- '*.asciidoc'
- '*.pdf'
asciidoc:
  ext: adoc
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    icons: font
    idseparator: _
    stylesdir: css
    source-highlighter: coderay