plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - guide-photovoltaique.md
theme: jekyll-theme-cayman
title: Guide sans prétention du photovoltaïque
subtitle: '21/09/2024 17:47:57 - v1.3.0'
description: Un guide permettant de comprendre comment fonctionne le photovoltaïque, les démarches, les devis ou même poser soi-même
show_downloads: true
