plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - guide-photovoltaique.md
theme: jekyll-theme-cayman
title: Guide sans prétention du photovoltaïque
subtitle: 'To update'
description: Un guide permettant de comprendre comment fonctionne le photovoltaïque, les démarches, les devis ou même poser soi-même
show_downloads: true
