name: Generate PDF and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Ubuntu packages
        run: |
          sudo apt-get update
          sudo apt-get install -y asciidoctor ruby-full build-essential zlib1g-dev

      - name: Install YQ
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.43.1/yq_linux_amd64
          sudo chmod a+x /usr/local/bin/yq

      - name: Install Ruby dependencies
        run: |
          sudo gem install asciidoctor-pdf
          sudo gem install coderay pygments.rb
          sudo gem install jekyll bundler

      - name: Generate web site and PDF file
        run: |
          export GEM_HOME="$(ruby -e "puts Gem.user_dir")"
          export PATH="${GEM_HOME}/bin:${PATH}"
          ./generate.sh
          git checkout Gemfile.lock

      - name: Switch to gh-pages branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch
          git checkout gh-pages

      - name: Init website structure
        run: |
          rm -f *.adoc Dockerfile LICENSE *.md *.sh *.rb *.asciidoc Gemfile* *.yml
          mv site/* ./
          rm -rf site

      - name: Commit website
        run: |
          git add .
          git commit -m "Update gh-pages"
          git push origin gh-pages

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: Guide photovoltaïque en format PDF
          draft: false
          prerelease: false

      - name: Upload guide-photovoltaique.pdf
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./guide-photovoltaique.pdf
          asset_name: guide-photovoltaique.pdf
          asset_content_type: application/pdf
