name: Generate PDF and Release

 

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Pandoc and pdflatex
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc pdflatext

      - name: Run script
        run: ./generate.sh

      - name: Copy guide-photovoltaique.md to gh-pages branch
        run: |
          git checkout -b gh-pages
          git add guide-photovoltaique.md
          git commit -m "Add photovoltaique.md to gh-pages"
          git push origin gh-pages

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: Guide photovoltaïque en format PDF
          draft: false
          prerelease: false

      - name: Upload guide-photovoltaique.pdf
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./guide-photovoltaique.pdf
          asset_name: guide-photovoltaique.pdf
          asset_content_type: application/pdf
